<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<NoWarn>$(NoWarn);NU1903</NoWarn>
		<PublishReadyToRun>false</PublishReadyToRun>
		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0-preview.1.25120.3" Condition="'$(TargetFramework)' == 'net10.0'" />		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.OpenApi" Version="2.0.0-preview8" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\" />
	</ItemGroup>

	<!-- بناء مشروع Angular فقط أثناء الـ Publish -->
	<Target Name="BuildAngular" BeforeTargets="Publish">
		<Exec WorkingDirectory="../client" Command="npm install" />
		<Exec WorkingDirectory="../client" Command="npm run build -- --configuration production" />

		<ItemGroup>
			<DistFiles Include="../client/dist/ashour-client/browser\**\*.*" Condition="Exists('../client/dist/ashour-client/browser')" />
			<DistFiles Include="../client/dist/ashour-client\**\*.*" Condition="!Exists('../client/dist/ashour-client/browser') And Exists('../client/dist/ashour-client')" />
		</ItemGroup>

		<Copy SourceFiles="@(DistFiles)" DestinationFolder="wwwroot\%(RecursiveDir)" SkipUnchangedFiles="true" />
	</Target>

</Project>